apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.jetblue.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: eventstore
  name: eventstore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eventstore
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose.jetblue.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: eventstore
    spec:
      containers:
      - env:
        - name: EVENTSTORE_CLUSTER_SIZE
          value: "1"
        - name: EVENTSTORE_EXT_HTTP_PORT
          value: "2113"
        - name: EVENTSTORE_EXT_TCP_PORT
          value: "1113"
        - name: EVENTSTORE_INT_HTTP_PORT
          value: "2112"
        - name: EVENTSTORE_INT_TCP_PORT
          value: "1112"
        image: eventstore
        imagePullPolicy: ""
        name: eventstore
        ports:
        - containerPort: 1112
        - containerPort: 1113
        - containerPort: 2112
        - containerPort: 2113
        resources: {}
        volumeMounts:
        - mountPath: /var/opt/eventstore
          name: notification-eventstore
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: notification-eventstore
        persistentVolumeClaim:
          claimName: notification-eventstore
status: {}
