apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.jetblue.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: eventstore
  name: eventstore
spec:
  ports:
  - name: "1112"
    port: 1112
    targetPort: 1112
  - name: "1113"
    port: 1113
    targetPort: 1113
  - name: "2112"
    port: 2112
    targetPort: 2112
  - name: "2113"
    port: 2113
    targetPort: 2113
  selector:
    io.kompose.service: eventstore
status:
  loadBalancer: {}
