apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.jetblue.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: publishing-api
  name: publishing-api
spec:
  ports:
  - name: "5103"
    port: 5103
    targetPort: 80
  - name: "9103"
    port: 9103
    targetPort: 81
  selector:
    io.kompose.service: publishing-api
status:
  loadBalancer: {}
