apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.jetblue.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: seq
  name: seq
spec:
  ports:
  - name: "5340"
    port: 5340
    targetPort: 80
  selector:
    io.kompose.service: seq
status:
  loadBalancer: {}
