apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.jetblue.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: subscribing-signalrhub
  name: subscribing-signalrhub
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: subscribing-signalrhub
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose.jetblue.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: subscribing-signalrhub
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: EventBusConnection
          value: 192.168.8.56
        - name: EventBusPassword
        - name: EventBusUserName
        - name: EventBusVirtualHost
        - name: IdentityUrl
          value: http://:5105
        - name: SubscribingUrl
          value: http://:5100
        image: subscribing-signalrhub
        imagePullPolicy: ""
        name: subscribing-signalrhub
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
