apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.jetblue.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: webmvc
  name: webmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webmvc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose.jetblue.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: webmvc
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: ConnectionString
          value: Server=sqldata;Database=Notifications.SubscriberDB;User Id=sa;Password=Pass@word
        - name: EventBusConnection
          value: 192.168.8.56
        - name: EventBusPassword
        - name: EventBusUserName
        - name: EventBusVirtualHost
        - name: EventStoreConnection
          value: ConnectTo=tcp://admin:changeit@eventstore:1113; HeartBeatTimeout=500;
            VerboseLogging=true
        - name: IdentityUrl
          value: http://:5105
        - name: IdentityUrlHC
          value: http://identity-api/hc
        - name: NotifyingURL
          value: http://notifying-api
        - name: SignalrHubUrl
          value: http://:5112
        image: webmvc
        imagePullPolicy: ""
        name: webmvc
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
