apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.jetblue.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: webstatus
  name: webstatus
spec:
  ports:
  - name: "5107"
    port: 5107
    targetPort: 80
  selector:
    io.kompose.service: webstatus
status:
  loadBalancer: {}
